<?php
if (! defined('ABSPATH')) exit;
/**
 * Helper to allow SVG tags through wp_kses
 */
function oone_kses_allowed_html_svg()
{
    return array(
        'svg' => array(
            'class'                 => true,
            'aria-hidden'           => true,
            'aria-labelledby'       => true,
            'role'                  => true,
            'viewBox'               => true,
            'viewbox'               => true,
            'preserveAspectRatio'   => true,
            'width'                 => true,
            'height'                => true,
            'xmlns'                 => true,
            'xmlns:xlink'           => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'stroke-linejoin'       => true,
            'fill-rule'             => true,
            'clip-rule'             => true,
            'style'                 => true,
            'opacity'               => true,
            'focusable'             => true,
        ),
        'g' => array( // Essential for grouped paths
            'class'                 => true,
            'style'                 => true,
            'fill'                  => true,
            'stroke'                => true,
            'opacity'               => true,
            'transform'             => true,
        ),
        'path' => array(
            'class'                 => true,
            'style'                 => true,
            'd'                     => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'stroke-linejoin'       => true,
            'opacity'               => true,
            'transform'             => true,
            'stroke-dasharray'      => true,
            'stroke-dashoffset'     => true,
            'clip-rule'             => true,
            'fill-rule'             => true,
        ),
        'rect' => array(
            'class'                 => true,
            'style'                 => true,
            'x'                     => true,
            'y'                     => true,
            'width'                 => true,
            'height'                => true,
            'rx'                    => true,
            'ry'                    => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'stroke-linejoin'       => true,
            'opacity'               => true,
            'transform'             => true,
        ),
        'circle' => array(
            'class'                 => true,
            'style'                 => true,
            'cx'                    => true,
            'cy'                    => true,
            'r'                     => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'opacity'               => true,
            'transform'             => true,
        ),
        'ellipse' => array(
            'class'     => true,
            'style'     => true,
            'cx'        => true,
            'cy'        => true,
            'rx'        => true,
            'ry'        => true,
            'fill'      => true,
            'stroke'    => true,
            'stroke-width' => true,
            'stroke-dasharray' => true,
            'transform' => true,
        ),
        'line' => array(
            'class'                 => true,
            'style'                 => true,
            'x1'                    => true,
            'y1'                    => true,
            'x2'                    => true,
            'y2'                    => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'transform'             => true,
        ),
        'polyline' => array(
            'class'                 => true,
            'style'                 => true,
            'points'                => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'stroke-linejoin'       => true,
            'transform'             => true,
        ),
        'polygon' => array(
            'class'                 => true,
            'style'                 => true,
            'points'                => true,
            'fill'                  => true,
            'stroke'                => true,
            'stroke-width'          => true,
            'stroke-linecap'        => true,
            'stroke-linejoin'       => true,
            'transform'             => true,
        ),
        'text' => array(
            'class'                 => true,
            'style'                 => true,
            'x'                     => true,
            'y'                     => true,
            'dx'                    => true,
            'dy'                    => true,
            'font-size'             => true,
            'text-anchor'           => true,
            'fill'                  => true,
            'font-family'           => true,
            'font-weight'           => true,
            'transform'             => true,
        ),
        'title' => array(),
        'defs'  => array(),
        'linearGradient' => array(
            'id'                    => true,
            'x1'                    => true,
            'y1'                    => true,
            'x2'                    => true,
            'y2'                    => true,
            'gradientUnits'         => true,
            'gradientTransform'     => true,
        ),
        'stop' => array(
            'offset'                => true,
            'stop-color'            => true,
            'stop-opacity'          => true,
        ),
        'clipPath' => array(
            'id'                    => true,
            'clipPathUnits'         => true,
        ),
        'use' => array(
            'href'                  => true,
            'xlink:href'            => true,
        ),
        'span' => array(
            'class' => true,
            'style' => true,
        ),
    );
}
function oone_svg($svg)
{
    if (empty($svg)) {
        return '';
    }

    return wp_kses($svg, oone_kses_allowed_html_svg());
}
