<?php
if (! defined('ABSPATH')) {
    exit;
}
/**
 * Register shared libraries early.
 */
function oone_register_shared_libs()
{
    $asset_file = plugin_dir_path(OONE_PLUGIN_FILE) . 'build/shared.asset.php';

    if (! file_exists($asset_file)) {
        return;
    }

    $asset_data = include $asset_file;

    // 1. Register shared JavaScript
    wp_register_script(
        'oone-shared-libs',
        plugins_url('build/shared.js', OONE_PLUGIN_FILE),
        $asset_data['dependencies'],
        $asset_data['version'],
        false // Load in head to ensure it's available early
    );

    // ✅ 2. THE BRIDGE: Attach the settings to the script we just registered
    $localized_data = array(
        'ajaxUrl'     => admin_url('admin-ajax.php'),
        'nonce'       => wp_create_nonce('oone_nonce'),
        'publicNonce' => wp_create_nonce('oone_public_nonce'),
        'adminNonce'  => wp_create_nonce('oone_admin_nonce'),
        'pluginUrl'   => plugins_url('/', OONE_PLUGIN_FILE),
        'assetMap'    => oone_get_asset_map(),
    );

    // ✅ Attach it to the OLD name (keeps your Settings/Admin pages working)
    wp_localize_script('oone-shared-libs', 'ooneSettings', $localized_data);

    // ✅ Attach it to the NEW name (fixes your Block AJAX calls)
    wp_localize_script('oone-shared-libs', 'ooneAjaxBridge', $localized_data);

    // 3. Register shared CSS
    $shared_css = plugin_dir_path(OONE_PLUGIN_FILE) . 'build/shared.css';
    if (file_exists($shared_css)) {
        wp_register_style(
            'oone-shared-styles',
            plugins_url('build/shared.css', OONE_PLUGIN_FILE),
            array(),
            $asset_data['version']
        );
    }
}
add_action('init', 'oone_register_shared_libs', 5);

/**
 * Enqueue shared libs in block editor with high priority.
 */
function oone_enqueue_editor_libs()
{
    wp_enqueue_script('oone-shared-libs');

    if (wp_style_is('oone-shared-styles', 'registered')) {
        wp_enqueue_style('oone-shared-styles');
    }
}
add_action('enqueue_block_editor_assets', 'oone_enqueue_editor_libs', 5);


/**
 * Global helper to load shared assets.
 * Call this function from any admin page to load React, Flatpickr, etc.
 */
function oone_load_shared_assets()
{
    wp_enqueue_script('oone-shared-libs');
    wp_enqueue_style('oone-shared-styles');
}


/**
 * Enqueue dashboard page-specific assets safely.
 */
function oone_enqueue_admin_dashboard_assets($hook)
{
    if (strpos($hook, 'oone-') === false) {
        return;
    }

    // Always load your shared framework foundation first
    wp_enqueue_script('oone-shared-libs');
    wp_enqueue_style('oone-shared-styles');


    // Tell the automated scanner that evaluating the current page parameter is safe here
    // phpcs:ignore WordPress.Security.NonceVerification.Recommended
    $current_tab = isset($_GET['page'])
        ? sanitize_text_field(wp_unslash($_GET['page']))
        : '';

    // Match the active page slug value and map it directly to your Webpack entries
    switch ($current_tab) {
        case 'oone-dashboard':
            oone_enqueue_page_specific_asset('dashboard-main');
            break;
        case 'oone-blocks':
            oone_enqueue_page_specific_asset('dashboard-blocks');
            break;
        case 'oone-form-entries':
        case 'oone-leads':
            oone_enqueue_page_specific_asset('dashboard-leads');
            break;
        case 'oone-settings':
            oone_enqueue_page_specific_asset('dashboard-settings');
            break;
        case 'oone-help':
            oone_enqueue_page_specific_asset('dashboard-help');
            break;

        case 'oone-upgrade-pro':
            oone_enqueue_page_specific_asset('dashboard-upgrade');
            break;
    }
}
add_action('admin_enqueue_scripts', 'oone_enqueue_admin_dashboard_assets');

/**
 * Helper function to safely read dependencies generated by Webpack 
 * and enqueue the file correctly.
 */
function oone_enqueue_page_specific_asset($handle)
{
    $asset_path = plugin_dir_path(OONE_PLUGIN_FILE) . "build/{$handle}.asset.php";
    $script_url = plugins_url("build/{$handle}.js", OONE_PLUGIN_FILE);

    if (file_exists($asset_path)) {
        // Automatically fetch the React dependencies, WordPress core scripts, and build version from Webpack
        $asset_data = include $asset_path;
        wp_enqueue_script($handle, $script_url, $asset_data['dependencies'], $asset_data['version'], true);
    } else {
        // Fallback array if asset compilation mapping is temporarily missing during build testing
        wp_enqueue_script($handle, $script_url, array('jquery', 'oone-shared-libs'), '1.0.0', true);
    }
}
